version: "3"

services:
  digi-tech-one:
    image: "digi-tech-one:latest"
    expose:
      - "3000"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - digi-tech-one
    ports:
      - "5000:4000"
  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  pgdata:
  # database:
  #   image: postgres
  #   deploy:
  #     mode: global
  #   environment:
  #     - POSTGRES_PASSWORD=miksad
  #   ports:
  #     - "5432:5432"
