version: "3"

services:
  digi-tech-one:
    image: "digi-tech-one:latest"
    expose:
      - "3000"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - digi-tech-one
    ports:
      - "5000:4000"


