version: "3"

services:
  postgres:
    image: postgres
    container_name: pgdb
    expose:
      - "3000"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - postgres
    ports:
      - 5000:4000
volumes:
  pgdata:
# postgres:
#   image: "miksad/postgres:version1.0"
#   expose:
#     - "3000"
#   environment:
#     POSTGRES_PASSWORD: postgres
# nginx:
#   image: nginx:latest
#   restart: always
#   volumes:
#     - ./nginx.conf:/etc/nginx/nginx.conf:ro
#   depends_on:
#     - postgres
#   ports:
#     - "5000:4000"
#   pgdb:
#     image: postgres
#     container_name: pgdb
#     environment:
#       - POSTGRES_DB=postgres
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     ports:
#       - 5433:5432
# volumes:
#   pgdata:
